#image: peterreisz/gitlab-ci-runner-java-node
image: 4wits/builder-java

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository
  NEXT_VERSION: 'patch'
  AWS_ACCESS_KEY_ID: AKIAIWR3HYDJJVRHJVHA
  AWS_SECRET_ACCESS_KEY: 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

stages:
  - test
  - build
  - deploy

build:
 stage: build
 script:
    - mvn clean install -DskipTests=true
  artifacts:
    paths:
    - target/*.jar
  only:
    - tags


test:
  stage: test
  script:
    - mvn clean install -DskipTests=false -Pdev


deploy:
  stage: deploy
  script:
    - curl --data "token=8d8faf8ba42f43b254c572ad91060d&
                   ref=integration&
                   variables[SERVICE_NAME]=$CI_PROJECT_NAME&
                   variables[SERVICE_VERSION]=$CI_BUILD_TAG"
                   https://4wits.githost.io/api/v3/projects/62/trigger/builds
  only:
    - tags
