FROM alopcas4wits/jdk8-dev:1.0
MAINTAINER Jonas Holtorf <Jonas.Holtorf@4wits.de>

#"-agentpath:/jrebel/lib/libjrebel64.so", "-Drebel.log.file=/jrebel.log",
#CMD ["java", "-Xdebug","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7000", "-Xmx200m", "-jar", "/app/app.jar"]

WORKDIR /app
ADD src/main/resources/startup-dev.sh /app/startup-dev.sh
ENTRYPOINT sh /app/startup-dev.sh

#CMD ["java", "-javaagent:/jrebel/jrebel.jar", "-Drebel.log.file=/jrebel.log", "-jar", "/app/app.jar"]

EXPOSE 8080
EXPOSE 7000
